### ISSUE TITLE
No group nomination cooldowns for configs

### ISSUE THREAD

**Issue by memoriesKB** [Stewart-Anubis/Mapchooser-Extended-Anubis-Edition#1]
Hello, I would like to know if you can put group nomination cooldowns into this plugin.
For example: ZE servers have ze_surf maps, we would like to put all ze_surf maps into cooldown if one is played.
or something like this:
![image](https://user-images.githubusercontent.com/1625524/103774439-9ea87780-503d-11eb-8550-767928604989.png)
thx a lot for response :3

**Comment by Stewart-Anubis** [comment]
There is no way to configure by group, but by map "Player Min-Max and Contdown", This plugin is as original as the altor and the editor did, just fixed some compilation errors in SM 1.10. I believe that the Plugin that does what do you want to be Mapchooser Ultimate . https://forums.alliedmods.net/showthread.php?t=134190
