### ISSUE TITLE
[Bug] RTV vote count

### ISSUE THREAD

**Issue by stunslave** [Stewart-Anubis/Mapchooser-Extended-Anubis-Edition#2]
RTV (Sometimes) counts players that connect and leave the server as a vote. 

Example: 3 players connect, 1 player leaves and the 2 players left try to RTV, but 3 votes are needed.

**Comment by Stewart-Anubis** [comment]
Good night, this plug was not developed by me, I just made corrections so that it was compiled in sourcemode 1.10. But I will take a look to fix the bug, it should not be counted the players that disconnect from the server. post the update here.

**Comment by stunslave** [comment]
Latest build.
Not fixed still happens.
![image](https://user-images.githubusercontent.com/47533535/105183012-61141600-5b36-11eb-8f3e-f8a5d585c009.png)

**Comment by Stewart-Anubis** [comment]
I think I found the problem, I modified it to not count observers or bots or GOTV. Test and tell me, Thank you.

**Comment by stunslave** [comment]
Looks like it might be working, Thanks.

**Comment by stunslave** [comment]
It brings up this error. 
![image](https://user-images.githubusercontent.com/47533535/105286189-7e8cc280-5bbe-11eb-99a6-9a10c11c980d.png)
It still works tho.

**Comment by Stewart-Anubis** [comment]
I put an IsClientInGame checker. Should resolve the error.
