### ISSUE TITLE
cooldowns reset after server restart

### ISSUE THREAD

**Issue by memoriesKB** [Stewart-Anubis/Mapchooser-Extended-Anubis-Edition#3]
I noticed that after we restart the server with this plugin, we can nominate the maps again that were played recently
for example:
we played biohazard2 at 2 a.m
server restarts at 5 a.m.
then i saw at 7 a.m. that we can nominate this map after the restart again, the cooldown was 45 maps, means you need to wait for 1-2 days to play this map again
do you know how to fix it please?

**Comment by Stewart-Anubis** [comment]
As I understand it, do you want the cooldown map count to remain even after the server restart?
If so, it would be a very complex modification, as it would have to be changed to use mysql instead of the configuration file. Maybe someday I'll work on it.

**Comment by memoriesKB** [comment]
ok thx, we will wait for it

**Comment by Stewart-Anubis** [comment]
Modification in mapchooser_extended to keep Cooldown even after restarting the server. Exchange file is in "configs / old_map_file.cfg". Alpha test version "mapchooser_extended_alpha.smx" replaces "mapchooser_extended.smx".

https://github.com/Stewart-Anubis/Mapchooser-Extended-Anubis-Edition/tree/main/addons/sourcemod/plugins
