### ISSUE TITLE
[Bug] RTV vote count

### ISSUE THREAD

**Issue by stunslave** [Stewart-Anubis/Mapchooser-Extended-Anubis-Edition#4]
RTV doesn't count players that are 3 or less.

Example: If there are 3 players connected and one player uses RTV it will start the map vote 1/1 .. same as if there are 2 players.
If there are 4 players the count works perfectly.. 

The **sm_rtv_needed** can be set to anything and it only counts one player when 2 or 3 players are connected.

very random shit :P

**Comment by Stewart-Anubis** [comment]
It may be because he has to search the configuration file for each rtv or player to connect if there is a delay in the server it can happen, I will change it to load the settings in a global on start map. But with that new settings will only take effect after changing or restart the map.

**Comment by Stewart-Anubis** [comment]
As I said this plugin is not mine, I'm just fixing bugs.
I don't have access to a public server, I do tests on a private test server and with Bots, situations with real players is difficult to test because I don't have accounts other than mine connected to my server. And some problems really only appear with many online players.
I appreciate the problem warnings. My steam https://steamcommunity.com/id/stewartbh
Updated, I added a command "! Playersrtv" that will show the number of players connected to the server, which are alive and in play (admin only).

**Comment by stunslave** [comment]
Chilled take your time fixing stuff.. There's no hurry. 
I have changed it to 0.80 which seems to fix the problem (0.80 is basically 0.60 on the plugin now) :)

^ Not on the newest version, will test that later when I have some time. 
Thanks.

**Comment by stunslave** [comment]
![image](https://user-images.githubusercontent.com/47533535/106009209-c3ce5a00-60c0-11eb-9a78-55a660580fb9.png)
![image](https://user-images.githubusercontent.com/47533535/106009304-dba5de00-60c0-11eb-9a65-e9be7b09add2.png)

sm_playersrtv is correct.
I have no idea what could be causing it, this is the latest version. (just added some colors) :)
I'll leave this issue open and I'll comment if figure anything out.

**Comment by Stewart-Anubis** [comment]
By the image is correct, you are a spectator "It doesn't count" and there is one more bot "It doesn't count" that is 2 real players in a game those 1 of 1. 1 of 2 only if the setting was at 100% .A Unless you wanted him to count bot and spectator. Sure does not count spectator but does not prevent him from asking for RTV.

**Comment by stunslave** [comment]
Na I have tested it multiple times with 4 players in-game and not in spec the vote shows 1/1 or 1/0. 

Could it be that moving into spec removes a player from the vote count, but when the player rejoins a team it doesn't add the player back to the vote count.

I will carry on test again with the new version.

**Comment by Stewart-Anubis** [comment]
Yes, I can change to your taste "Private", currently it works like this. RTV counts "only", players live and in play (does not count bots), and if someone votes RTV and disconnects or becomes a spectator, their vote is automatically removed and will have to vote again.
